#!/usr/bin/env python3
"""
OpenObserve Alert Forwarder
"""

from flask import Flask, request, jsonify
import requests
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
import os
import json

app = Flask(__name__)

# Configuración
SMTP_HOST = os.getenv("SMTP_HOST", "smtp.gmail.com")
SMTP_PORT = int(os.getenv("SMTP_PORT", "587"))
SMTP_USER = os.getenv("SMTP_USER", "dnestrada@unis.edu.gt")
SMTP_PASSWORD = os.getenv("SMTP_PASSWORD", "")
SLACK_WEBHOOK = os.getenv("SLACK_WEBHOOK_URL", "")
EMAIL_RECIPIENTS = os.getenv("EMAIL_RECIPIENTS", "dnestrada@unis.edu.gt,jflores@unis.edu.gt").split(",")

def format_openobserve_email(alert_data):
    
    # Extraer información de la alerta de Grafana
    alerts = alert_data.get('alerts', [])
    if not alerts:
        return None
    
    alert = alerts[0]
    alert_name = alert.get('labels', {}).get('alertname', 'Unknown Alert')
    status = alert.get('status', 'unknown')
    severity = alert.get('labels', {}).get('severity', 'unknown')
    summary = alert.get('annotations', {}).get('summary', '')
    description = alert.get('annotations', {}).get('description', '')
    starts_at = alert.get('startsAt', datetime.now().isoformat())
    
    body = f"""


****************************************************
*                                                  *
*        OPENOBSERVE ALERT NOTIFICATION           *
*                                                  *
****************************************************


══════════════════════════════════════════════════
ALERT INFORMATION
══════════════════════════════════════════════════

Alert Name    : {alert_name}
Status        : {status}
Severity      : {severity}


══════════════════════════════════════════════════
METADATA
══════════════════════════════════════════════════

Organization  : default
Stream Type   : metrics
Stream Name   : {alert_name}


══════════════════════════════════════════════════
DETAILS
══════════════════════════════════════════════════

Summary       : {summary}
Description   : {description}


══════════════════════════════════════════════════
TIMING
══════════════════════════════════════════════════

Triggered At  : {starts_at}


══════════════════════════════════════════════════
QUICK ACTIONS
══════════════════════════════════════════════════

View Alert    : http://localhost:5080/alerts
Dashboard     : http://localhost:5080/dashboards
Streams       : http://localhost:5080/streams



****************************************************

This alert was generated by OpenObserve
Open Source Observability Platform

Platform URL: http://localhost:5080

****************************************************


"""
    
    return {
        'subject': f'[OpenObserve] {alert_name} - {severity}',
        'body': body
    }

def send_email(subject, body, recipients):
    """Envía el email"""
    try:
        msg = MIMEMultipart()
        msg['From'] = SMTP_USER
        msg['To'] = ', '.join(recipients)
        msg['Subject'] = subject
        
        msg.attach(MIMEText(body, 'plain'))
        
        server = smtplib.SMTP(SMTP_HOST, SMTP_PORT)
        server.starttls()
        server.login(SMTP_USER, SMTP_PASSWORD)
        text = msg.as_string()
        server.sendmail(SMTP_USER, recipients, text)
        server.quit()
        
        return True
    except Exception as e:
        print(f"Error sending email: {e}")
        return False

def format_openobserve_slack(alert_data):
    """Formatea el mensaje de Slack como si viniera de OpenObserve"""
    
    alerts = alert_data.get('alerts', [])
    if not alerts:
        return None
    
    alert = alerts[0]
    alert_name = alert.get('labels', {}).get('alertname', 'Unknown Alert')
    status = alert.get('status', 'unknown')
    severity = alert.get('labels', {}).get('severity', 'unknown')
    summary = alert.get('annotations', {}).get('summary', '')
    description = alert.get('annotations', {}).get('description', '')
    starts_at = alert.get('startsAt', datetime.now().isoformat())
    
    # Emoji según severidad
    emoji = "🔴" if severity == "critical" else "🟡"
    
    message = {
        "text": f"{emoji} *OpenObserve Alert Notification*",
        "blocks": [
            {
                "type": "header",
                "text": {
                    "type": "plain_text",
                    "text": f"📊 OpenObserve Alert",
                    "emoji": True
                }
            },
            {
                "type": "section",
                "fields": [
                    {
                        "type": "mrkdwn",
                        "text": f"*Alert Name:*\n{alert_name}"
                    },
                    {
                        "type": "mrkdwn",
                        "text": f"*Status:*\n{status}"
                    }
                ]
            },
            {
                "type": "section",
                "fields": [
                    {
                        "type": "mrkdwn",
                        "text": f"*Severity:*\n{severity}"
                    },
                    {
                        "type": "mrkdwn",
                        "text": f"*Organization:*\ndefault"
                    }
                ]
            },
            {
                "type": "divider"
            },
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f"*Summary:*\n{summary}"
                }
            },
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f"*Description:*\n{description}"
                }
            },
            {
                "type": "divider"
            },
            {
                "type": "section",
                "fields": [
                    {
                        "type": "mrkdwn",
                        "text": f"*Stream Type:*\nmetrics"
                    },
                    {
                        "type": "mrkdwn",
                        "text": f"*Triggered At:*\n{starts_at}"
                    }
                ]
            },
            {
                "type": "actions",
                "elements": [
                    {
                        "type": "button",
                        "text": {
                            "type": "plain_text",
                            "text": "View Alert 🔗",
                            "emoji": True
                        },
                        "url": "http://localhost:5080/alerts"
                    },
                    {
                        "type": "button",
                        "text": {
                            "type": "plain_text",
                            "text": "Dashboard 📊",
                            "emoji": True
                        },
                        "url": "http://localhost:5080/dashboards"
                    }
                ]
            },
            {
                "type": "context",
                "elements": [
                    {
                        "type": "mrkdwn",
                        "text": "_Powered by OpenObserve_ 🚀 | <http://localhost:5080|View Platform>"
                    }
                ]
            }
        ]
    }
    
    return message

def send_slack(message):
    """Envía el mensaje a Slack"""
    try:
        response = requests.post(SLACK_WEBHOOK, json=message)
        return response.status_code == 200
    except Exception as e:
        print(f"Error sending Slack message: {e}")
        return False

@app.route('/webhook', methods=['POST'])
def webhook():
    """Endpoint que recibe las alertas de Grafana"""
    
    try:
        alert_data = request.json
        print(f"Received alert: {json.dumps(alert_data, indent=2)}")
        
        # Formatear y enviar email
        email_content = format_openobserve_email(alert_data)
        if email_content:
            email_sent = send_email(
                email_content['subject'],
                email_content['body'],
                EMAIL_RECIPIENTS
            )
            print(f"Email sent: {email_sent}")
        
        # Formatear y enviar Slack
        slack_message = format_openobserve_slack(alert_data)
        if slack_message:
            slack_sent = send_slack(slack_message)
            print(f"Slack sent: {slack_sent}")
        
        return jsonify({"status": "success"}), 200
        
    except Exception as e:
        print(f"Error processing webhook: {e}")
        return jsonify({"status": "error", "message": str(e)}), 500

@app.route('/health', methods=['GET'])
def health():
    """Health check endpoint"""
    return jsonify({"status": "healthy"}), 200

if __name__ == '__main__':
    print("Starting OpenObserve Alert Forwarder...")
    print(f"Webhook URL: http://localhost:5001/webhook")
    app.run(host='0.0.0.0', port=5001, debug=True)

