services:
  # Backend - Java API con SQLite
  backend:
    build:
      context: ./backv4
      dockerfile: Dockerfile
    container_name: ensurance-backend
    ports:
      - "8081:8081"
    environment:
      - DB_TYPE=sqlite
      - JAVA_OPTS=-Ddb.type=sqlite
      - SERVER_PORT=8081
    volumes:
      # Montar el archivo de base de datos para persistencia
      - ./backv4/pharmacy_db.sqlite:/app/pharmacy_db.sqlite
    networks:
      - ensurance-network
    healthcheck:
      test: ["CMD-SHELL", "netstat -tuln | grep :8081 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Frontend - Vue.js
  frontend:
    build:
      context: ./ensurance
      dockerfile: Dockerfile
    container_name: ensurance-frontend
    ports:
      - "9008:9008"
    environment:
      - VITE_API_URL=http://localhost:8081
      - VITE_IP=localhost
      - VITE_PORT=9008
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - ensurance-network
    volumes:
      # Para desarrollo: montar el código fuente
      - ./ensurance/src:/app/src
    stdin_open: true
    tty: true

networks:
  ensurance-network:
    driver: bridge

volumes:
  sqlite_data: 